// ICT Screener – Vercel Serverless Function
// Data: Yahoo Finance v8 chart API (no crumb · no API key)
// 1169 stocks across all sectors

const STOCKS = [
  ["AAPL","Apple Inc","Technology"],
  ["MSFT","Microsoft Corp","Technology"],
  ["NVDA","NVIDIA Corp","Technology"],
  ["AVGO","Broadcom Inc","Technology"],
  ["AMD","Advanced Micro Devices","Technology"],
  ["QCOM","Qualcomm Inc","Technology"],
  ["TXN","Texas Instruments","Technology"],
  ["AMAT","Applied Materials","Technology"],
  ["LRCX","Lam Research","Technology"],
  ["MU","Micron Technology","Technology"],
  ["KLAC","KLA Corp","Technology"],
  ["ADI","Analog Devices","Technology"],
  ["MRVL","Marvell Technology","Technology"],
  ["INTC","Intel Corp","Technology"],
  ["ARM","Arm Holdings","Technology"],
  ["ALAB","Astera Labs","Technology"],
  ["CRDO","Credo Technology","Technology"],
  ["SMCI","Super Micro Computer","Technology"],
  ["DELL","Dell Technologies","Technology"],
  ["HPQ","HP Inc","Technology"],
  ["CSCO","Cisco Systems","Technology"],
  ["MPWR","Monolithic Power Systems","Technology"],
  ["MCHP","Microchip Technology","Technology"],
  ["ON","ON Semiconductor","Technology"],
  ["CDNS","Cadence Design Systems","Technology"],
  ["ANSS","Ansys Inc","Technology"],
  ["RMBS","Rambus Inc","Technology"],
  ["ONTO","Onto Innovation","Technology"],
  ["AMBA","Ambarella Inc","Technology"],
  ["MTSI","MACOM Technology","Technology"],
  ["SWKS","Skyworks Solutions","Technology"],
  ["SITM","SiTime Corp","Technology"],
  ["ALGM","Allegro MicroSystems","Technology"],
  ["AEIS","Advanced Energy Industries","Technology"],
  ["LSCC","Lattice Semiconductor","Technology"],
  ["ENTG","Entegris Inc","Technology"],
  ["MKSI","MKS Instruments","Technology"],
  ["MRCY","Mercury Systems","Technology"],
  ["COHU","Cohu Inc","Technology"],
  ["FORM","FormFactor Inc","Technology"],
  ["ACLS","Axcelis Technologies","Technology"],
  ["DIOD","Diodes Inc","Technology"],
  ["CEVA","CEVA Inc","Technology"],
  ["PI","Impinj Inc","Technology"],
  ["NOVT","Novanta Inc","Technology"],
  ["VIAV","Viavi Solutions","Technology"],
  ["NSIT","Insight Enterprises","Technology"],
  ["WOLF","Wolfspeed Inc","Technology"],
  ["ENVX","Enovix Corp","Technology"],
  ["IPGP","IPG Photonics","Technology"],
  ["IIVI","Coherent Corp","Technology"],
  ["OLED","Universal Display Corp","Technology"],
  ["NTNX","Nutanix Inc","Technology"],
  ["PSTG","Pure Storage","Technology"],
  ["NTAP","NetApp Inc","Technology"],
  ["STX","Seagate Technology","Technology"],
  ["WDC","Western Digital","Technology"],
  ["ZBRA","Zebra Technologies","Technology"],
  ["HPE","Hewlett Packard Enterprise","Technology"],
  ["GLW","Corning Inc","Technology"],
  ["JNPR","Juniper Networks","Technology"],
  ["KEYS","Keysight Technologies","Technology"],
  ["TRMB","Trimble Inc","Technology"],
  ["IDCC","InterDigital Inc","Technology"],
  ["SMTC","Semtech Corp","Technology"],
  ["SLAB","Silicon Laboratories","Technology"],
  ["QRVO","Qorvo Inc","Technology"],
  ["HIMX","Himax Technologies","Technology"],
  ["AOSL","Alpha Omega Semiconductor","Technology"],
  ["AEHR","Aehr Test Systems","Technology"],
  ["ACMR","ACM Research","Technology"],
  ["POWI","Power Integrations","Technology"],
  ["KLIC","Kulicke and Soffa","Technology"],
  ["MRAM","Everspin Technologies","Technology"],
  ["APLD","Applied Digital Corp","Technology"],
  ["DSGX","Descartes Systems","Technology"],
  ["EXTR","Extreme Networks","Technology"],
  ["FFIV","F5 Inc","Technology"],
  ["FARO","FARO Technologies","Technology"],
  ["GRMN","Garmin Ltd","Technology"],
  ["LFUS","Littelfuse Inc","Technology"],
  ["ITRI","Itron Inc","Technology"],
  ["PCTY","Paylocity Holding","Technology"],
  ["SPSC","SPS Commerce","Technology"],
  ["CLFD","Clearfield Inc","Technology"],
  ["CALX","Calix Inc","Technology"],
  ["ATEN","A10 Networks","Technology"],
  ["HLIT","Harmonic Inc","Technology"],
  ["INSG","Inseego Corp","Technology"],
  ["CAMP","CalAmp Corp","Technology"],
  ["DGII","Digi International","Technology"],
  ["CNXC","Concentrix Corp","Technology"],
  ["HOLI","Hollysys Automation","Technology"],
  ["HURN","Huron Consulting","Technology"],
  ["SAIC","Science Applications Intl","Technology"],
  ["SSYS","Stratasys Ltd","Technology"],
  ["TTEC","TTEC Holdings","Technology"],
  ["XPERI","Xperi Inc","Technology"],
  ["ZETA","Zeta Global Holdings","Technology"],
  ["EGHT","8x8 Inc","Technology"],
  ["EVTC","EVERTEC Inc","Technology"],
  ["FRSH","Freshworks Inc","Technology"],
  ["GDYN","Grid Dynamics Holdings","Technology"],
  ["NDSN","Nordson Corp","Technology"],
  ["PLXS","Plexus Corp","Technology"],
  ["PRFT","Perficient Inc","Technology"],
  ["VNET","VNET Group","Technology"],
  ["YELP","Yelp Inc","Technology"],
  ["META","Meta Platforms","Software"],
  ["GOOGL","Alphabet Inc","Software"],
  ["GOOG","Alphabet Class C","Software"],
  ["CRM","Salesforce Inc","Software"],
  ["NOW","ServiceNow Inc","Software"],
  ["ADBE","Adobe Inc","Software"],
  ["INTU","Intuit Inc","Software"],
  ["WDAY","Workday Inc","Software"],
  ["SNOW","Snowflake Inc","Software"],
  ["DDOG","Datadog Inc","Software"],
  ["HUBS","HubSpot Inc","Software"],
  ["PANW","Palo Alto Networks","Software"],
  ["CRWD","CrowdStrike Holdings","Software"],
  ["ZS","Zscaler Inc","Software"],
  ["OKTA","Okta Inc","Software"],
  ["FTNT","Fortinet Inc","Software"],
  ["S","SentinelOne","Software"],
  ["PLTR","Palantir Technologies","Software"],
  ["PATH","UiPath Inc","Software"],
  ["AI","C3.ai Inc","Software"],
  ["SOUN","SoundHound AI","Software"],
  ["ASAN","Asana Inc","Software"],
  ["MNDY","Monday.com","Software"],
  ["MDB","MongoDB Inc","Software"],
  ["GTLB","GitLab Inc","Software"],
  ["VEEV","Veeva Systems","Software"],
  ["PCOR","Procore Technologies","Software"],
  ["TOST","Toast Inc","Software"],
  ["BILL","Bill.com Holdings","Software"],
  ["DT","Dynatrace Inc","Software"],
  ["ESTC","Elastic NV","Software"],
  ["CFLT","Confluent Inc","Software"],
  ["BRZE","Braze Inc","Software"],
  ["ZI","ZoomInfo Technologies","Software"],
  ["MANH","Manhattan Associates","Software"],
  ["PAYC","Paycom Software","Software"],
  ["RPD","Rapid7 Inc","Software"],
  ["QLYS","Qualys Inc","Software"],
  ["TENB","Tenable Holdings","Software"],
  ["VRNS","Varonis Systems","Software"],
  ["RNG","RingCentral Inc","Software"],
  ["FIVN","Five9 Inc","Software"],
  ["FOUR","Shift4 Payments","Software"],
  ["TTD","The Trade Desk","Software"],
  ["ADSK","Autodesk Inc","Software"],
  ["NCNO","nCino Inc","Software"],
  ["APPN","Appian Corp","Software"],
  ["PEGA","Pegasystems Inc","Software"],
  ["UPWK","Upwork Inc","Software"],
  ["BBAI","BigBear.ai Holdings","Software"],
  ["CWAN","Clearwater Analytics","Software"],
  ["DLB","Dolby Laboratories","Software"],
  ["DOMO","Domo Inc","Software"],
  ["EVBG","Everbridge Inc","Software"],
  ["EXLS","ExlService Holdings","Software"],
  ["INST","Instructure Holdings","Software"],
  ["JAMF","Jamf Holding Corp","Software"],
  ["LPSN","LivePerson Inc","Software"],
  ["MGNI","Magnite Inc","Software"],
  ["PAR","PAR Technology","Software"],
  ["PRO","PROS Holdings","Software"],
  ["QTWO","Q2 Holdings","Software"],
  ["RAMP","LiveRamp Holdings","Software"],
  ["RDDT","Reddit Inc","Software"],
  ["SCWX","SecureWorks Corp","Software"],
  ["SMAR","Smartsheet Inc","Software"],
  ["SQSP","Squarespace Inc","Software"],
  ["SSTK","Shutterstock Inc","Software"],
  ["TASK","TaskUs Inc","Software"],
  ["TRMR","Tremor International","Software"],
  ["TUYA","Tuya Inc","Software"],
  ["XMTR","Xometry Inc","Software"],
  ["YEXT","Yext Inc","Software"],
  ["GEN","Gen Digital Inc","Software"],
  ["DCBO","Docebo Inc","Software"],
  ["ALRM","Alarm.com Holdings","Software"],
  ["ACIW","ACI Worldwide","Software"],
  ["ACVA","ACV Auctions","Software"],
  ["AGYS","Agilysys Inc","Software"],
  ["AZPN","Aspen Technology","Software"],
  ["BLKB","Blackbaud Inc","Software"],
  ["CDAY","Ceridian HCM Holding","Software"],
  ["CERT","Certara Inc","Software"],
  ["COUP","Coupa Software","Software"],
  ["DBX","Dropbox Inc","Software"],
  ["BOX","Box Inc","Software"],
  ["DOCN","DigitalOcean Holdings","Software"],
  ["ENFN","Enfusion Inc","Software"],
  ["EXFY","Expensify Inc","Software"],
  ["FROG","JFrog Ltd","Software"],
  ["GWRE","Guidewire Software","Software"],
  ["KARO","Karooooo Ltd","Software"],
  ["KNBE","KnowBe4 Inc","Software"],
  ["LASR","nLIGHT Inc","Software"],
  ["MAPS","WM Technology","Software"],
  ["MTTR","Matterport Inc","Software"],
  ["NABL","N-able Inc","Software"],
  ["NEWR","New Relic Inc","Software"],
  ["OPEN","Opendoor Technologies","Software"],
  ["PAGS","PagSeguro Digital","Software"],
  ["PING","Ping Identity Holding","Software"],
  ["PTC","PTC Inc","Software"],
  ["STNE","StoneCo Ltd","Software"],
  ["SVMK","SurveyMonkey","Software"],
  ["TDOC","Teladoc Health","Software"],
  ["TTGT","TechTarget Inc","Software"],
  ["TWLO","Twilio Inc","Software"],
  ["BAND","Bandwidth Inc","Software"],
  ["U","Unity Software","Software"],
  ["VERI","Veritone Inc","Software"],
  ["WEX","WEX Inc","Software"],
  ["DOCU","DocuSign Inc","Software"],
  ["HCP","HashiCorp Inc","Software"],
  ["SMRT","SmartRent Inc","Software"],
  ["AMZN","Amazon.com Inc","Cloud"],
  ["NET","Cloudflare Inc","Cloud"],
  ["AKAM","Akamai Technologies","Cloud"],
  ["FSLY","Fastly Inc","Cloud"],
  ["INFA","Informatica Inc","Cloud"],
  ["CVLT","Commvault Systems","Cloud"],
  ["EPAM","EPAM Systems","Cloud"],
  ["GLOB","Globant SA","Cloud"],
  ["BIDU","Baidu Inc","Cloud"],
  ["JD","JD.com Inc","Cloud"],
  ["NTES","NetEase Inc","Cloud"],
  ["PDD","PDD Holdings","Cloud"],
  ["BABA","Alibaba Group","Cloud"],
  ["SE","Sea Ltd","Cloud"],
  ["GRAB","Grab Holdings","Cloud"],
  ["GLBE","Global-E Online","Cloud"],
  ["DLO","DLocal Ltd","Cloud"],
  ["MELI","MercadoLibre Inc","Cloud"],
  ["JPM","JPMorgan Chase","Financials"],
  ["BAC","Bank of America","Financials"],
  ["WFC","Wells Fargo","Financials"],
  ["GS","Goldman Sachs","Financials"],
  ["MS","Morgan Stanley","Financials"],
  ["C","Citigroup Inc","Financials"],
  ["V","Visa Inc","Financials"],
  ["MA","Mastercard Inc","Financials"],
  ["PYPL","PayPal Holdings","Financials"],
  ["SQ","Block Inc","Financials"],
  ["AFRM","Affirm Holdings","Financials"],
  ["SOFI","SoFi Technologies","Financials"],
  ["HOOD","Robinhood Markets","Financials"],
  ["COIN","Coinbase Global","Financials"],
  ["MSTR","MicroStrategy Inc","Financials"],
  ["BLK","BlackRock Inc","Financials"],
  ["BX","Blackstone Inc","Financials"],
  ["KKR","KKR Co Inc","Financials"],
  ["APO","Apollo Global Management","Financials"],
  ["SCHW","Charles Schwab","Financials"],
  ["AXP","American Express","Financials"],
  ["COF","Capital One Financial","Financials"],
  ["FI","Fiserv Inc","Financials"],
  ["CME","CME Group Inc","Financials"],
  ["NDAQ","Nasdaq Inc","Financials"],
  ["MSCI","MSCI Inc","Financials"],
  ["MCO","Moodys Corp","Financials"],
  ["SPGI","S&P Global Inc","Financials"],
  ["ICE","Intercontinental Exchange","Financials"],
  ["USB","US Bancorp","Financials"],
  ["PNC","PNC Financial Services","Financials"],
  ["TFC","Truist Financial","Financials"],
  ["ALLY","Ally Financial Inc","Financials"],
  ["DFS","Discover Financial","Financials"],
  ["SYF","Synchrony Financial","Financials"],
  ["IBKR","Interactive Brokers","Financials"],
  ["LPLA","LPL Financial Holdings","Financials"],
  ["RJF","Raymond James","Financials"],
  ["SF","Stifel Financial Corp","Financials"],
  ["VIRT","Virtu Financial","Financials"],
  ["MQ","Marqeta Inc","Financials"],
  ["WU","Western Union","Financials"],
  ["GPN","Global Payments","Financials"],
  ["FIS","Fidelity National Info","Financials"],
  ["BR","Broadridge Financial","Financials"],
  ["FDS","FactSet Research","Financials"],
  ["CBOE","Cboe Global Markets","Financials"],
  ["AMP","Ameriprise Financial","Financials"],
  ["TROW","T Rowe Price Group","Financials"],
  ["IVZ","Invesco Ltd","Financials"],
  ["BEN","Franklin Resources","Financials"],
  ["AMG","Affiliated Managers Group","Financials"],
  ["BK","Bank of New York Mellon","Financials"],
  ["STT","State Street Corp","Financials"],
  ["NTRS","Northern Trust Corp","Financials"],
  ["AIG","American Intl Group","Financials"],
  ["ALL","Allstate Corp","Financials"],
  ["AFL","Aflac Inc","Financials"],
  ["MET","MetLife Inc","Financials"],
  ["PRU","Prudential Financial","Financials"],
  ["HIG","Hartford Financial Services","Financials"],
  ["TRV","Travelers Companies","Financials"],
  ["ACGL","Arch Capital Group","Financials"],
  ["WRB","WR Berkley Corp","Financials"],
  ["ERIE","Erie Indemnity","Financials"],
  ["CINF","Cincinnati Financial","Financials"],
  ["MKL","Markel Corp","Financials"],
  ["KNSL","Kinsale Capital Group","Financials"],
  ["CFG","Citizens Financial Group","Financials"],
  ["CMA","Comerica Inc","Financials"],
  ["FITB","Fifth Third Bancorp","Financials"],
  ["HBAN","Huntington Bancshares","Financials"],
  ["KEY","KeyCorp","Financials"],
  ["MTB","MT Bank Corp","Financials"],
  ["RF","Regions Financial Corp","Financials"],
  ["ZION","Zions Bancorporation","Financials"],
  ["WAL","Western Alliance Bancorp","Financials"],
  ["FHN","First Horizon Corp","Financials"],
  ["FCNCA","First Citizens Bancshares","Financials"],
  ["SNV","Synovus Financial","Financials"],
  ["SSB","SouthState Corp","Financials"],
  ["EWBC","East West Bancorp","Financials"],
  ["CATY","Cathay General Bancorp","Financials"],
  ["SFBS","ServisFirst Bancshares","Financials"],
  ["BOKF","BOK Financial Corp","Financials"],
  ["TCBI","Texas Capital Bancshares","Financials"],
  ["COLB","Columbia Banking System","Financials"],
  ["PPBI","Pacific Premier Bancorp","Financials"],
  ["NLY","Annaly Capital Management","Financials"],
  ["AGNC","AGNC Investment Corp","Financials"],
  ["STWD","Starwood Property Trust","Financials"],
  ["BXMT","Blackstone Mortgage Trust","Financials"],
  ["KREF","KKR Real Estate Finance","Financials"],
  ["PMT","PennyMac Mortgage Trust","Financials"],
  ["RITM","Rithm Capital Corp","Financials"],
  ["CACC","Credit Acceptance Corp","Financials"],
  ["ECPG","Encore Capital Group","Financials"],
  ["OMF","OneMain Financial","Financials"],
  ["OPFI","OppFi Inc","Financials"],
  ["LC","LendingClub Corp","Financials"],
  ["FUTU","Futu Holdings","Financials"],
  ["EVR","Evercore Inc","Financials"],
  ["HLI","Houlihan Lokey Inc","Financials"],
  ["MC","Moelis Co","Financials"],
  ["LAZ","Lazard Ltd","Financials"],
  ["PIPR","Piper Sandler Companies","Financials"],
  ["MKTX","MarketAxess Holdings","Financials"],
  ["ARCC","Ares Capital Corp","Financials"],
  ["MAIN","Main Street Capital","Financials"],
  ["HTGC","Hercules Capital","Financials"],
  ["GBDC","Golub Capital BDC","Financials"],
  ["GLAD","Gladstone Capital","Financials"],
  ["GAIN","Gladstone Investment","Financials"],
  ["GSBD","Goldman Sachs BDC","Financials"],
  ["EFC","Ellington Financial","Financials"],
  ["UWMC","UWM Holdings","Financials"],
  ["PFSI","PennyMac Financial","Financials"],
  ["GHLD","Guild Holdings","Financials"],
  ["LLY","Eli Lilly and Co","Healthcare"],
  ["UNH","UnitedHealth Group","Healthcare"],
  ["JNJ","Johnson Johnson","Healthcare"],
  ["ABT","Abbott Laboratories","Healthcare"],
  ["TMO","Thermo Fisher Scientific","Healthcare"],
  ["DHR","Danaher Corp","Healthcare"],
  ["MDT","Medtronic plc","Healthcare"],
  ["SYK","Stryker Corp","Healthcare"],
  ["BSX","Boston Scientific","Healthcare"],
  ["ISRG","Intuitive Surgical","Healthcare"],
  ["EW","Edwards Lifesciences","Healthcare"],
  ["AMGN","Amgen Inc","Healthcare"],
  ["GILD","Gilead Sciences","Healthcare"],
  ["BIIB","Biogen Inc","Healthcare"],
  ["REGN","Regeneron Pharmaceuticals","Healthcare"],
  ["VRTX","Vertex Pharmaceuticals","Healthcare"],
  ["MRNA","Moderna Inc","Healthcare"],
  ["PFE","Pfizer Inc","Healthcare"],
  ["MRK","Merck Co","Healthcare"],
  ["BMY","Bristol-Myers Squibb","Healthcare"],
  ["NVO","Novo Nordisk","Healthcare"],
  ["NTRA","Natera Inc","Healthcare"],
  ["CRSP","CRISPR Therapeutics","Healthcare"],
  ["RXRX","Recursion Pharmaceuticals","Healthcare"],
  ["RVMD","Revolution Medicines","Healthcare"],
  ["CI","The Cigna Group","Healthcare"],
  ["HUM","Humana Inc","Healthcare"],
  ["CVS","CVS Health Corp","Healthcare"],
  ["IDXX","IDEXX Laboratories","Healthcare"],
  ["HOLX","Hologic Inc","Healthcare"],
  ["DXCM","DexCom Inc","Healthcare"],
  ["ALGN","Align Technology","Healthcare"],
  ["VKTX","Viking Therapeutics","Healthcare"],
  ["AXSM","Axsome Therapeutics","Healthcare"],
  ["KRYS","Krystal Biotech","Healthcare"],
  ["SRPT","Sarepta Therapeutics","Healthcare"],
  ["TGTX","TG Therapeutics","Healthcare"],
  ["EXAS","Exact Sciences Corp","Healthcare"],
  ["PACB","Pacific Biosciences","Healthcare"],
  ["TXG","10x Genomics","Healthcare"],
  ["RARE","Ultragenyx Pharmaceutical","Healthcare"],
  ["MORF","Morphic Holding","Healthcare"],
  ["KYMR","Kymera Therapeutics","Healthcare"],
  ["JANX","Janux Therapeutics","Healthcare"],
  ["LNTH","Lantheus Holdings","Healthcare"],
  ["PODD","Insulet Corp","Healthcare"],
  ["INMD","InMode Ltd","Healthcare"],
  ["NVCR","NovoCure Ltd","Healthcare"],
  ["MCK","McKesson Corp","Healthcare"],
  ["CAH","Cardinal Health","Healthcare"],
  ["DGX","Quest Diagnostics","Healthcare"],
  ["LH","Labcorp","Healthcare"],
  ["CRL","Charles River Laboratories","Healthcare"],
  ["ICLR","ICON plc","Healthcare"],
  ["MEDP","Medpace Holdings","Healthcare"],
  ["ZBH","Zimmer Biomet Holdings","Healthcare"],
  ["STE","STERIS plc","Healthcare"],
  ["BAX","Baxter International","Healthcare"],
  ["BDX","Becton Dickinson","Healthcare"],
  ["COO","Cooper Companies","Healthcare"],
  ["MTD","Mettler-Toledo International","Healthcare"],
  ["WAT","Waters Corp","Healthcare"],
  ["PKI","PerkinElmer Inc","Healthcare"],
  ["BIO","Bio-Rad Laboratories","Healthcare"],
  ["TECH","Bio-Techne Corp","Healthcare"],
  ["BEAM","Beam Therapeutics","Healthcare"],
  ["EDIT","Editas Medicine","Healthcare"],
  ["NTLA","Intellia Therapeutics","Healthcare"],
  ["DNLI","Denali Therapeutics","Healthcare"],
  ["ARVN","Arvinas Inc","Healthcare"],
  ["KRTX","Karuna Therapeutics","Healthcare"],
  ["RCKT","Rocket Pharmaceuticals","Healthcare"],
  ["RCUS","Arcus Biosciences","Healthcare"],
  ["REPL","Replimune Group","Healthcare"],
  ["ACAD","Acadia Pharmaceuticals","Healthcare"],
  ["AGIO","Agios Pharmaceuticals","Healthcare"],
  ["ALNY","Alnylam Pharmaceuticals","Healthcare"],
  ["ARQT","Arcutis Biotherapeutics","Healthcare"],
  ["ARWR","Arrowhead Pharmaceuticals","Healthcare"],
  ["ATRC","AtriCure Inc","Healthcare"],
  ["AUPH","Aurinia Pharmaceuticals","Healthcare"],
  ["AVDL","Avadel Pharmaceuticals","Healthcare"],
  ["BCRX","BioCryst Pharmaceuticals","Healthcare"],
  ["BLUE","bluebird bio","Healthcare"],
  ["BMEA","Biomea Fusion","Healthcare"],
  ["BPMC","Blueprint Medicines","Healthcare"],
  ["CARA","Cara Therapeutics","Healthcare"],
  ["CERE","Cerevel Therapeutics","Healthcare"],
  ["CLDX","Celldex Therapeutics","Healthcare"],
  ["COLL","Collegium Pharmaceutical","Healthcare"],
  ["CPRX","Catalyst Pharmaceuticals","Healthcare"],
  ["CTLT","Catalent Inc","Healthcare"],
  ["CYTK","Cytokinetics Inc","Healthcare"],
  ["DVAX","Dynavax Technologies","Healthcare"],
  ["ESTA","Establishment Labs","Healthcare"],
  ["EYE","National Vision Holdings","Healthcare"],
  ["FATE","Fate Therapeutics","Healthcare"],
  ["FGEN","FibroGen Inc","Healthcare"],
  ["FOLD","Amicus Therapeutics","Healthcare"],
  ["GKOS","Glaukos Corp","Healthcare"],
  ["HALO","Halozyme Therapeutics","Healthcare"],
  ["HRMY","Harmony Biosciences","Healthcare"],
  ["IART","Integra LifeSciences","Healthcare"],
  ["IMGN","ImmunoGen Inc","Healthcare"],
  ["IONS","Ionis Pharmaceuticals","Healthcare"],
  ["IRTC","iRhythm Technologies","Healthcare"],
  ["ITCI","Intra-Cellular Therapies","Healthcare"],
  ["KDMN","Kadmon Holdings","Healthcare"],
  ["LGND","Ligand Pharmaceuticals","Healthcare"],
  ["LQDA","Liquidia Corp","Healthcare"],
  ["MDGL","Madrigal Pharmaceuticals","Healthcare"],
  ["MKUL","Molekule Group","Healthcare"],
  ["MLTX","MoonLake Immunotherapeutics","Healthcare"],
  ["MNKD","MannKind Corp","Healthcare"],
  ["NNOX","Nano-X Imaging","Healthcare"],
  ["OCGN","Ocugen Inc","Healthcare"],
  ["OMCL","Omnicell Inc","Healthcare"],
  ["OPTN","Option Care Health","Healthcare"],
  ["OSCR","Oscar Health","Healthcare"],
  ["PETQ","PetIQ Inc","Healthcare"],
  ["PRVA","Privia Health Group","Healthcare"],
  ["PTGX","Protagonist Therapeutics","Healthcare"],
  ["RGEN","Repligen Corp","Healthcare"],
  ["SDGR","Schrodinger Inc","Healthcare"],
  ["SGEN","Seagen Inc","Healthcare"],
  ["STAA","STAAR Surgical","Healthcare"],
  ["SURF","Surface Oncology","Healthcare"],
  ["TMDX","TransMedics Group","Healthcare"],
  ["TVTX","Travere Therapeutics","Healthcare"],
  ["TWST","Twist Bioscience","Healthcare"],
  ["UTHR","United Therapeutics","Healthcare"],
  ["VCYT","Veracyte Inc","Healthcare"],
  ["VIVO","Meridian Bioscience","Healthcare"],
  ["VRDN","Viridian Therapeutics","Healthcare"],
  ["VSTM","Verastem Inc","Healthcare"],
  ["VTRS","Viatris Inc","Healthcare"],
  ["XNCR","Xencor Inc","Healthcare"],
  ["YMAB","Y-mAbs Therapeutics","Healthcare"],
  ["ZEAL","Zealand Pharma","Healthcare"],
  ["ZGEN","Zymeworks Inc","Healthcare"],
  ["ZNTL","Zentalis Pharmaceuticals","Healthcare"],
  ["AGEN","Agenus Inc","Healthcare"],
  ["AHCO","AdaptHealth Corp","Healthcare"],
  ["AMEH","Apollo Medical Holdings","Healthcare"],
  ["AMPH","Amphastar Pharmaceuticals","Healthcare"],
  ["AMRN","Amarin Corp","Healthcare"],
  ["ANAB","AnaptysBio Inc","Healthcare"],
  ["ANIK","Anika Therapeutics","Healthcare"],
  ["ANIP","ANI Pharmaceuticals","Healthcare"],
  ["APTO","Aptose Biosciences","Healthcare"],
  ["AQST","Aquestive Therapeutics","Healthcare"],
  ["ARDX","Ardelyx Inc","Healthcare"],
  ["ARGX","argenx SE","Healthcare"],
  ["ATEC","Alphatec Holdings","Healthcare"],
  ["ATHA","Athira Pharma","Healthcare"],
  ["AUTL","Autolus Therapeutics","Healthcare"],
  ["AVEO","AVEO Pharmaceuticals","Healthcare"],
  ["AVNS","Avanos Medical","Healthcare"],
  ["AWH","Amneal Pharmaceuticals","Healthcare"],
  ["AXDX","Accelerate Diagnostics","Healthcare"],
  ["AXGN","AxoGen Inc","Healthcare"],
  ["AXNX","Axonics Modulation Technologies","Healthcare"],
  ["BDSI","BioDelivery Sciences","Healthcare"],
  ["BIOC","Biocept Inc","Healthcare"],
  ["BIOL","Biolase Inc","Healthcare"],
  ["BLFS","BioLife Solutions","Healthcare"],
  ["CEMI","Chembio Diagnostics","Healthcare"],
  ["CLSD","Clearside Biomedical","Healthcare"],
  ["COCP","Cocrystal Pharma","Healthcare"],
  ["CRIS","Curis Inc","Healthcare"],
  ["CRMD","CorMedix Inc","Healthcare"],
  ["CUTR","Cutera Inc","Healthcare"],
  ["DH","Definitive Healthcare","Healthcare"],
  ["DMTK","DermTech Inc","Healthcare"],
  ["DRNA","Dicerna Pharmaceuticals","Healthcare"],
  ["DTIL","Precision BioSciences","Healthcare"],
  ["EHC","Encompass Health","Healthcare"],
  ["EHTH","eHealth Inc","Healthcare"],
  ["EIGR","Eiger BioPharmaceuticals","Healthcare"],
  ["EKSO","Ekso Bionics Holdings","Healthcare"],
  ["ELEV","Elevation Oncology","Healthcare"],
  ["EMBC","Embecta Corp","Healthcare"],
  ["ENDS","Endo International","Healthcare"],
  ["EOLS","Evolent Health","Healthcare"],
  ["ERAS","Erasca Inc","Healthcare"],
  ["ESNT","Essent Group","Healthcare"],
  ["ESPR","Esperion Therapeutics","Healthcare"],
  ["ETNB","89bio Inc","Healthcare"],
  ["EVFM","Evofem Biosciences","Healthcare"],
  ["FLGT","Fulgent Genetics","Healthcare"],
  ["FUSN","Fusion Pharmaceuticals","Healthcare"],
  ["GALT","Galectin Therapeutics","Healthcare"],
  ["GBIO","Generation Bio","Healthcare"],
  ["GLPG","Galapagos NV","Healthcare"],
  ["GLSI","Greenwich LifeSciences","Healthcare"],
  ["GMAB","Genmab AS","Healthcare"],
  ["GTHX","G1 Therapeutics","Healthcare"],
  ["HARP","Harpoon Therapeutics","Healthcare"],
  ["HCSG","Healthcare Services Group","Healthcare"],
  ["HLVX","HilleVax Inc","Healthcare"],
  ["HOOK","Hookipa Pharma","Healthcare"],
  ["HROW","Harrow Health","Healthcare"],
  ["HSKA","Heska Corp","Healthcare"],
  ["ICAD","iCAD Inc","Healthcare"],
  ["IMNM","Immunome Inc","Healthcare"],
  ["IMVT","Immunovant Inc","Healthcare"],
  ["INFU","InfuSystem Holdings","Healthcare"],
  ["INGN","Inogen Inc","Healthcare"],
  ["IONM","Assure Holdings Corp","Healthcare"],
  ["IPSC","Century Therapeutics","Healthcare"],
  ["ISEE","IVERIC bio Inc","Healthcare"],
  ["KALA","Kala Bio","Healthcare"],
  ["KROS","Keros Therapeutics","Healthcare"],
  ["LHDX","Lucira Health","Healthcare"],
  ["LMND","Lemonade Inc","Healthcare"],
  ["MASI","Masimo Corp","Healthcare"],
  ["MBIO","Mustang Bio","Healthcare"],
  ["MCRB","Seres Therapeutics","Healthcare"],
  ["MDRX","Allscripts Healthcare","Healthcare"],
  ["MGNX","MacroGenics Inc","Healthcare"],
  ["MIRM","Mirum Pharmaceuticals","Healthcare"],
  ["MNOV","MediciNova Inc","Healthcare"],
  ["MPLN","MultiPlan Corp","Healthcare"],
  ["MREO","Mereo Biopharma Group","Healthcare"],
  ["MRTX","Mirati Therapeutics","Healthcare"],
  ["MRVI","Maravai LifeSciences","Healthcare"],
  ["MTEM","Molecular Templates","Healthcare"],
  ["MTNB","Matinas BioPharma","Healthcare"],
  ["MXCT","MaxCyte Inc","Healthcare"],
  ["NBTB","NBT Bancorp","Healthcare"],
  ["NCNA","NuCana plc","Healthcare"],
  ["NEO","NeoGenomics Inc","Healthcare"],
  ["NERV","Minerva Neurosciences","Healthcare"],
  ["NGNE","Neurogene Inc","Healthcare"],
  ["NKTR","Nektar Therapeutics","Healthcare"],
  ["NMRA","Neumora Therapeutics","Healthcare"],
  ["NRBO","NeuroBo Pharmaceuticals","Healthcare"],
  ["NVAX","Novavax Inc","Healthcare"],
  ["NVTA","Invitae Corp","Healthcare"],
  ["OBIO","Orchestra BioMed Holdings","Healthcare"],
  ["OCSL","Oaktree Specialty Lending","Healthcare"],
  ["OCUP","Ocuphire Pharma","Healthcare"],
  ["OGN","Organon Co","Healthcare"],
  ["OMPS","Omeros Corp","Healthcare"],
  ["ONCT","Oncternal Therapeutics","Healthcare"],
  ["OPK","OPKO Health","Healthcare"],
  ["OPRX","OptimizeRx Corp","Healthcare"],
  ["ORTX","Orchard Therapeutics","Healthcare"],
  ["OSUR","OraSure Technologies","Healthcare"],
  ["OTLK","Outlook Therapeutics","Healthcare"],
  ["OVID","Ovid Therapeutics","Healthcare"],
  ["PAHC","Phibro Animal Health","Healthcare"],
  ["RIGL","Rigel Pharmaceuticals","Healthcare"],
  ["SVRA","Savara Inc","Healthcare"],
  ["TSHA","Taysha Gene Therapies","Healthcare"],
  ["TYME","Tyme Technologies","Healthcare"],
  ["VCNX","Vaccinex Inc","Healthcare"],
  ["VXRT","Vaxart Inc","Healthcare"],
  ["XBIT","XBiotech Inc","Healthcare"],
  ["XENE","Xenon Pharmaceuticals","Healthcare"],
  ["TSLA","Tesla Inc","Consumer"],
  ["HD","Home Depot","Consumer"],
  ["LOW","Lowes Companies","Consumer"],
  ["NKE","Nike Inc","Consumer"],
  ["SBUX","Starbucks Corp","Consumer"],
  ["MCD","McDonalds Corp","Consumer"],
  ["CMG","Chipotle Mexican Grill","Consumer"],
  ["LULU","Lululemon Athletica","Consumer"],
  ["BKNG","Booking Holdings","Consumer"],
  ["ABNB","Airbnb Inc","Consumer"],
  ["UBER","Uber Technologies","Consumer"],
  ["LYFT","Lyft Inc","Consumer"],
  ["DASH","DoorDash Inc","Consumer"],
  ["DKNG","DraftKings Inc","Consumer"],
  ["RCL","Royal Caribbean Group","Consumer"],
  ["CCL","Carnival Corp","Consumer"],
  ["WYNN","Wynn Resorts","Consumer"],
  ["MGM","MGM Resorts International","Consumer"],
  ["TJX","TJX Companies","Consumer"],
  ["ROST","Ross Stores","Consumer"],
  ["BURL","Burlington Stores","Consumer"],
  ["FIVE","Five Below Inc","Consumer"],
  ["CROX","Crocs Inc","Consumer"],
  ["DECK","Deckers Outdoor","Consumer"],
  ["ELF","elf Beauty","Consumer"],
  ["ULTA","Ulta Beauty","Consumer"],
  ["ANF","Abercrombie Fitch","Consumer"],
  ["CELH","Celsius Holdings","Consumer"],
  ["WING","Wingstop Inc","Consumer"],
  ["CVNA","Carvana Co","Consumer"],
  ["WMT","Walmart Inc","Consumer"],
  ["COST","Costco Wholesale","Consumer"],
  ["TGT","Target Corp","Consumer"],
  ["DG","Dollar General","Consumer"],
  ["DLTR","Dollar Tree","Consumer"],
  ["SHOP","Shopify Inc","Consumer"],
  ["ETSY","Etsy Inc","Consumer"],
  ["EBAY","eBay Inc","Consumer"],
  ["KR","Kroger Co","Consumer"],
  ["MNST","Monster Beverage","Consumer"],
  ["KHC","Kraft Heinz Co","Consumer"],
  ["QSR","Restaurant Brands International","Consumer"],
  ["YUM","Yum Brands","Consumer"],
  ["DPZ","Dominos Pizza","Consumer"],
  ["EAT","Brinker International","Consumer"],
  ["TXRH","Texas Roadhouse","Consumer"],
  ["CAKE","Cheesecake Factory","Consumer"],
  ["SHAK","Shake Shack Inc","Consumer"],
  ["BLMN","Bloomin Brands","Consumer"],
  ["BJRI","BJs Restaurants","Consumer"],
  ["JACK","Jack in the Box","Consumer"],
  ["PZZA","Papa Johns International","Consumer"],
  ["DENN","Dennys Corp","Consumer"],
  ["NDLS","Noodles Company","Consumer"],
  ["LOCO","El Pollo Loco","Consumer"],
  ["RRGB","Red Robin Gourmet Burgers","Consumer"],
  ["FAT","FAT Brands Inc","Consumer"],
  ["AEO","American Eagle Outfitters","Consumer"],
  ["URBN","Urban Outfitters","Consumer"],
  ["GPS","Gap Inc","Consumer"],
  ["COLM","Columbia Sportswear","Consumer"],
  ["SKX","Skechers USA","Consumer"],
  ["FL","Foot Locker","Consumer"],
  ["HBI","Hanesbrands Inc","Consumer"],
  ["PVH","PVH Corp","Consumer"],
  ["TPR","Tapestry Inc","Consumer"],
  ["RL","Ralph Lauren Corp","Consumer"],
  ["GES","Guess Inc","Consumer"],
  ["LEVI","Levi Strauss Co","Consumer"],
  ["SBH","Sally Beauty Holdings","Consumer"],
  ["SIG","Signet Jewelers","Consumer"],
  ["W","Wayfair Inc","Consumer"],
  ["REAL","The RealReal","Consumer"],
  ["RVLV","Revolve Group","Consumer"],
  ["RENT","Rent the Runway","Consumer"],
  ["CHWY","Chewy Inc","Consumer"],
  ["PETS","PetMeds Express","Consumer"],
  ["FLWS","1-800-Flowers.com","Consumer"],
  ["COUR","Coursera Inc","Consumer"],
  ["DUOL","Duolingo Inc","Consumer"],
  ["CHGG","Chegg Inc","Consumer"],
  ["HIMS","Hims Hers Health","Consumer"],
  ["PTON","Peloton Interactive","Consumer"],
  ["NLS","Nautilus Inc","Consumer"],
  ["KMX","CarMax Inc","Consumer"],
  ["AN","AutoNation Inc","Consumer"],
  ["LAD","Lithia Motors","Consumer"],
  ["ABG","Asbury Automotive Group","Consumer"],
  ["VRM","Vroom Inc","Consumer"],
  ["LVS","Las Vegas Sands","Consumer"],
  ["CZR","Caesars Entertainment","Consumer"],
  ["CHDN","Churchill Downs","Consumer"],
  ["PENN","PENN Entertainment","Consumer"],
  ["NCLH","Norwegian Cruise Line","Consumer"],
  ["TRIP","TripAdvisor Inc","Consumer"],
  ["EXPE","Expedia Group","Consumer"],
  ["HLT","Hilton Worldwide","Consumer"],
  ["MAR","Marriott International","Consumer"],
  ["H","Hyatt Hotels Corp","Consumer"],
  ["CHH","Choice Hotels International","Consumer"],
  ["WH","Wyndham Hotels Resorts","Consumer"],
  ["TNL","Travel Leisure Co","Consumer"],
  ["ARCO","Arcos Dorados Holdings","Consumer"],
  ["CBRL","Cracker Barrel","Consumer"],
  ["DIN","Dine Brands Global","Consumer"],
  ["FWRG","First Watch Restaurant Group","Consumer"],
  ["PTLO","Portillos Inc","Consumer"],
  ["RICK","RCI Hospitality Holdings","Consumer"],
  ["VAC","Marriott Vacations Worldwide","Consumer"],
  ["FOXF","Fox Factory Holding","Consumer"],
  ["LESL","Leslies Inc","Consumer"],
  ["PLAY","Dave Busters Entertainment","Consumer"],
  ["BOOT","Boot Barn Holdings","Consumer"],
  ["OLLIE","Ollies Bargain Outlet","Consumer"],
  ["BIG","Big Lots Inc","Consumer"],
  ["BBWI","Bath Body Works","Consumer"],
  ["OLLI","Ollies Bargain Outlet","Consumer"],
  ["SFM","Sprouts Farmers Market","Consumer"],
  ["CATO","Cato Corp","Consumer"],
  ["DXLG","Destination XL Group","Consumer"],
  ["HIBB","Hibbett Inc","Consumer"],
  ["XOM","Exxon Mobil Corp","Energy"],
  ["CVX","Chevron Corp","Energy"],
  ["COP","ConocoPhillips","Energy"],
  ["EOG","EOG Resources","Energy"],
  ["SLB","Schlumberger Ltd","Energy"],
  ["HAL","Halliburton Co","Energy"],
  ["BKR","Baker Hughes","Energy"],
  ["DVN","Devon Energy Corp","Energy"],
  ["FANG","Diamondback Energy","Energy"],
  ["MPC","Marathon Petroleum","Energy"],
  ["VLO","Valero Energy","Energy"],
  ["PSX","Phillips 66","Energy"],
  ["OXY","Occidental Petroleum","Energy"],
  ["LNG","Cheniere Energy","Energy"],
  ["OVV","Ovintiv Inc","Energy"],
  ["MTDR","Matador Resources","Energy"],
  ["KMI","Kinder Morgan","Energy"],
  ["WMB","Williams Companies","Energy"],
  ["OKE","ONEOK Inc","Energy"],
  ["ET","Energy Transfer","Energy"],
  ["AR","Antero Resources","Energy"],
  ["EQT","EQT Corp","Energy"],
  ["RRC","Range Resources","Energy"],
  ["CHK","Chesapeake Energy","Energy"],
  ["SWN","Southwestern Energy","Energy"],
  ["TRGP","Targa Resources","Energy"],
  ["MRO","Marathon Oil","Energy"],
  ["HES","Hess Corp","Energy"],
  ["APA","APA Corp","Energy"],
  ["SM","SM Energy","Energy"],
  ["CPE","Callon Petroleum","Energy"],
  ["PR","Permian Resources","Energy"],
  ["VTLE","Vital Energy","Energy"],
  ["TALO","Talos Energy","Energy"],
  ["REI","Ring Energy Inc","Energy"],
  ["WHD","Cactus Inc","Energy"],
  ["LBRT","Liberty Energy Inc","Energy"],
  ["NEX","NexTier Completion Solutions","Energy"],
  ["MPLX","MPLX LP","Energy"],
  ["EPD","Enterprise Products Partners","Energy"],
  ["PAA","Plains All American Pipeline","Energy"],
  ["AM","Antero Midstream","Energy"],
  ["ENLC","EnLink Midstream","Energy"],
  ["WES","Western Midstream Partners","Energy"],
  ["HESM","Hess Midstream Partners","Energy"],
  ["GEL","Genesis Energy","Energy"],
  ["USAC","USA Compression Partners","Energy"],
  ["VNOM","Viper Energy Partners","Energy"],
  ["BSM","Black Stone Minerals","Energy"],
  ["CQP","Cheniere Energy Partners","Energy"],
  ["FLNG","Flex LNG Ltd","Energy"],
  ["GLNG","Golar LNG Ltd","Energy"],
  ["NFE","New Fortress Energy","Energy"],
  ["KOS","Kosmos Energy","Energy"],
  ["VET","Vermilion Energy","Energy"],
  ["NOG","Northern Oil Gas","Energy"],
  ["CIVI","Civitas Resources","Energy"],
  ["CRK","Comstock Resources","Energy"],
  ["GPOR","Gulfport Energy","Energy"],
  ["MNRL","Brigham Minerals","Energy"],
  ["TRP","TC Energy Corp","Energy"],
  ["ENB","Enbridge Inc","Energy"],
  ["SU","Suncor Energy","Energy"],
  ["CNQ","Canadian Natural Resources","Energy"],
  ["CVE","Cenovus Energy","Energy"],
  ["DMLP","Dorchester Minerals","Energy"],
  ["VVV","Valvoline Inc","Energy"],
  ["DK","Delek US Holdings","Energy"],
  ["PBF","PBF Energy Inc","Energy"],
  ["PARR","Par Pacific Holdings","Energy"],
  ["CLMT","Calumet Specialty Products","Energy"],
  ["ENPH","Enphase Energy","Clean Energy"],
  ["FSLR","First Solar Inc","Clean Energy"],
  ["SEDG","SolarEdge Technologies","Clean Energy"],
  ["BE","Bloom Energy Corp","Clean Energy"],
  ["PLUG","Plug Power Inc","Clean Energy"],
  ["RIVN","Rivian Automotive","Clean Energy"],
  ["LCID","Lucid Group","Clean Energy"],
  ["NIO","NIO Inc","Clean Energy"],
  ["XPEV","XPeng Inc","Clean Energy"],
  ["LI","Li Auto Inc","Clean Energy"],
  ["CHPT","ChargePoint Holdings","Clean Energy"],
  ["BLNK","Blink Charging","Clean Energy"],
  ["FLNC","Fluence Energy","Clean Energy"],
  ["STEM","Stem Inc","Clean Energy"],
  ["ARRY","Array Technologies","Clean Energy"],
  ["RUN","Sunrun Inc","Clean Energy"],
  ["NOVA","Sunnova Energy","Clean Energy"],
  ["MAXN","Maxeon Solar Technologies","Clean Energy"],
  ["CSIQ","Canadian Solar Inc","Clean Energy"],
  ["JKS","JinkoSolar Holding","Clean Energy"],
  ["DQ","Daqo New Energy","Clean Energy"],
  ["SPWR","SunPower Corp","Clean Energy"],
  ["GEVO","Gevo Inc","Clean Energy"],
  ["AMRC","Ameresco Inc","Clean Energy"],
  ["SHLS","Shoals Technologies","Clean Energy"],
  ["FTCI","FTC Solar","Clean Energy"],
  ["BEEM","Beam Global","Clean Energy"],
  ["EVGO","EVgo Inc","Clean Energy"],
  ["NEE","NextEra Energy","Clean Energy"],
  ["AES","AES Corp","Clean Energy"],
  ["BEP","Brookfield Renewable Partners","Clean Energy"],
  ["CWEN","Clearway Energy","Clean Energy"],
  ["HASI","Hannon Armstrong","Clean Energy"],
  ["NKLA","Nikola Corp","Clean Energy"],
  ["GOEV","Canoo Inc","Clean Energy"],
  ["FSR","Fisker Inc","Clean Energy"],
  ["MULN","Mullen Automotive","Clean Energy"],
  ["WKHS","Workhorse Group","Clean Energy"],
  ["HYZN","Hyzon Motors","Clean Energy"],
  ["PTRA","Proterra Inc","Clean Energy"],
  ["GE","GE Aerospace","Industrials"],
  ["HON","Honeywell International","Industrials"],
  ["CAT","Caterpillar Inc","Industrials"],
  ["DE","Deere Company","Industrials"],
  ["RTX","RTX Corp","Industrials"],
  ["LMT","Lockheed Martin","Industrials"],
  ["BA","Boeing Co","Industrials"],
  ["NOC","Northrop Grumman","Industrials"],
  ["GD","General Dynamics","Industrials"],
  ["AXON","Axon Enterprise","Industrials"],
  ["KTOS","Kratos Defense Security","Industrials"],
  ["JOBY","Joby Aviation","Industrials"],
  ["ACHR","Archer Aviation","Industrials"],
  ["DRS","Leonardo DRS","Industrials"],
  ["HEI","HEICO Corp","Industrials"],
  ["TDG","TransDigm Group","Industrials"],
  ["LHX","L3Harris Technologies","Industrials"],
  ["TXT","Textron Inc","Industrials"],
  ["HWM","Howmet Aerospace","Industrials"],
  ["SPR","Spirit AeroSystems","Industrials"],
  ["MOOG","Moog Inc","Industrials"],
  ["CW","Curtiss-Wright Corp","Industrials"],
  ["LDOS","Leidos Holdings","Industrials"],
  ["CACI","CACI International","Industrials"],
  ["BAH","Booz Allen Hamilton","Industrials"],
  ["UNP","Union Pacific Corp","Industrials"],
  ["CSX","CSX Corp","Industrials"],
  ["NSC","Norfolk Southern Corp","Industrials"],
  ["FDX","FedEx Corp","Industrials"],
  ["UPS","United Parcel Service","Industrials"],
  ["DAL","Delta Air Lines","Industrials"],
  ["UAL","United Airlines Holdings","Industrials"],
  ["AAL","American Airlines Group","Industrials"],
  ["LUV","Southwest Airlines","Industrials"],
  ["ALK","Alaska Air Group","Industrials"],
  ["JBLU","JetBlue Airways","Industrials"],
  ["HA","Hawaiian Holdings","Industrials"],
  ["URI","United Rentals","Industrials"],
  ["PWR","Quanta Services","Industrials"],
  ["ETN","Eaton Corp","Industrials"],
  ["EMR","Emerson Electric","Industrials"],
  ["ROK","Rockwell Automation","Industrials"],
  ["AME","AMETEK Inc","Industrials"],
  ["PH","Parker-Hannifin Corp","Industrials"],
  ["DOV","Dover Corp","Industrials"],
  ["TT","Trane Technologies","Industrials"],
  ["CARR","Carrier Global","Industrials"],
  ["OTIS","Otis Worldwide","Industrials"],
  ["IR","Ingersoll Rand","Industrials"],
  ["IDEX","IDEX Corp","Industrials"],
  ["GNRC","Generac Holdings","Industrials"],
  ["XYL","Xylem Inc","Industrials"],
  ["ROP","Roper Technologies","Industrials"],
  ["GWW","W.W. Grainger","Industrials"],
  ["MSM","MSC Industrial Direct","Industrials"],
  ["FAST","Fastenal Co","Industrials"],
  ["SNA","Snap-on Inc","Industrials"],
  ["SWK","Stanley Black Decker","Industrials"],
  ["MAS","Masco Corp","Industrials"],
  ["TREX","Trex Company","Industrials"],
  ["BLDR","Builders FirstSource","Industrials"],
  ["IBP","Installed Building Products","Industrials"],
  ["BECN","Beacon Roofing Supply","Industrials"],
  ["BLD","TopBuild Corp","Industrials"],
  ["SUM","Summit Materials","Industrials"],
  ["WM","Waste Management","Industrials"],
  ["RSG","Republic Services","Industrials"],
  ["CLH","Clean Harbors","Industrials"],
  ["VMC","Vulcan Materials","Industrials"],
  ["MLM","Martin Marietta Materials","Industrials"],
  ["EXP","Eagle Materials","Industrials"],
  ["EME","EMCOR Group","Industrials"],
  ["MTZ","MasTec Inc","Industrials"],
  ["STRL","Sterling Infrastructure","Industrials"],
  ["DY","Dycom Industries","Industrials"],
  ["MYRG","MYR Group","Industrials"],
  ["J","Jacobs Solutions","Industrials"],
  ["ACM","AECOM","Industrials"],
  ["TTEK","Tetra Tech Inc","Industrials"],
  ["KBR","KBR Inc","Industrials"],
  ["FLR","Fluor Corp","Industrials"],
  ["AL","Air Lease Corp","Industrials"],
  ["GXO","GXO Logistics","Industrials"],
  ["ARCB","ArcBest Corp","Industrials"],
  ["JBHT","J.B. Hunt Transport","Industrials"],
  ["WERN","Werner Enterprises","Industrials"],
  ["LSTR","Landstar System","Industrials"],
  ["SAIA","Saia Inc","Industrials"],
  ["XPO","XPO Inc","Industrials"],
  ["ESAB","ESAB Corp","Industrials"],
  ["EPAC","Enerpac Tool Group","Industrials"],
  ["ROAD","Construction Partners","Industrials"],
  ["PRIM","Primoris Services","Industrials"],
  ["TPC","Tutor Perini Corp","Industrials"],
  ["ASGN","ASGN Inc","Industrials"],
  ["CWST","Casella Waste Systems","Industrials"],
  ["GATX","GATX Corp","Industrials"],
  ["HII","Huntington Ingalls Industries","Industrials"],
  ["WWD","Woodward Inc","Industrials"],
  ["KFRC","Kforce Inc","Industrials"],
  ["MHH","Mastech Digital","Industrials"],
  ["RHI","Robert Half International","Industrials"],
  ["KELYA","Kelly Services","Industrials"],
  ["MAN","ManpowerGroup Inc","Industrials"],
  ["EXPO","Exponent Inc","Industrials"],
  ["TDY","Teledyne Technologies","Industrials"],
  ["HXL","Hexcel Corp","Industrials"],
  ["NPO","EnPro Industries","Industrials"],
  ["LNN","Lindsay Corp","Industrials"],
  ["FCX","Freeport-McMoRan","Materials"],
  ["NEM","Newmont Corp","Materials"],
  ["AA","Alcoa Corp","Materials"],
  ["NUE","Nucor Corp","Materials"],
  ["STLD","Steel Dynamics","Materials"],
  ["CLF","Cleveland-Cliffs Inc","Materials"],
  ["ALB","Albemarle Corp","Materials"],
  ["MP","MP Materials Corp","Materials"],
  ["LAC","Lithium Americas","Materials"],
  ["LIN","Linde plc","Materials"],
  ["APD","Air Products and Chemicals","Materials"],
  ["SHW","Sherwin-Williams Co","Materials"],
  ["ECL","Ecolab Inc","Materials"],
  ["CF","CF Industries Holdings","Materials"],
  ["MOS","The Mosaic Company","Materials"],
  ["ATI","ATI Inc","Materials"],
  ["CMC","Commercial Metals","Materials"],
  ["X","United States Steel","Materials"],
  ["RS","Reliance Steel Aluminum","Materials"],
  ["KALU","Kaiser Aluminum","Materials"],
  ["WLK","Westlake Chemical","Materials"],
  ["CE","Celanese Corp","Materials"],
  ["HUN","Huntsman Corp","Materials"],
  ["EMN","Eastman Chemical","Materials"],
  ["OLN","Olin Corp","Materials"],
  ["RPM","RPM International","Materials"],
  ["PPG","PPG Industries","Materials"],
  ["ASH","Ashland Inc","Materials"],
  ["IP","International Paper","Materials"],
  ["PKG","Packaging Corp of America","Materials"],
  ["GPK","Graphic Packaging Holding","Materials"],
  ["SEE","Sealed Air Corp","Materials"],
  ["SLGN","Silgan Holdings","Materials"],
  ["BERY","Berry Global Group","Materials"],
  ["GEF","Greif Inc","Materials"],
  ["SON","Sonoco Products","Materials"],
  ["AEM","Agnico Eagle Mines","Materials"],
  ["KGC","Kinross Gold Corp","Materials"],
  ["CDE","Coeur Mining","Materials"],
  ["HL","Hecla Mining","Materials"],
  ["BTG","B2Gold Corp","Materials"],
  ["OR","Osisko Gold Royalties","Materials"],
  ["WPM","Wheaton Precious Metals","Materials"],
  ["GOLD","Barrick Gold Corp","Materials"],
  ["AG","First Majestic Silver","Materials"],
  ["PAAS","Pan American Silver","Materials"],
  ["CMP","Compass Minerals","Materials"],
  ["KWR","Quaker Chemical","Materials"],
  ["TROX","Tronox Holdings","Materials"],
  ["LTHM","Livent Corp","Materials"],
  ["PLL","Piedmont Lithium","Materials"],
  ["SQM","Sociedad Quimica y Minera","Materials"],
  ["VALE","Vale SA","Materials"],
  ["RIO","Rio Tinto plc","Materials"],
  ["BHP","BHP Group Ltd","Materials"],
  ["SCCO","Southern Copper Corp","Materials"],
  ["TECK","Teck Resources","Materials"],
  ["CSL","Carlisle Companies","Materials"],
  ["GCP","GCP Applied Technologies","Materials"],
  ["LOOP","Loop Industries","Materials"],
  ["IONR","ioneer Ltd","Materials"],
  ["MTOR","Meritor Inc","Materials"],
  ["MTRN","Materion Corp","Materials"],
  ["MTRX","Matrix Service Co","Materials"],
  ["T","AT&T Inc","Communications"],
  ["VZ","Verizon Communications","Communications"],
  ["TMUS","T-Mobile US","Communications"],
  ["NFLX","Netflix Inc","Communications"],
  ["DIS","Walt Disney Co","Communications"],
  ["CMCSA","Comcast Corp","Communications"],
  ["SPOT","Spotify Technology","Communications"],
  ["PINS","Pinterest Inc","Communications"],
  ["SNAP","Snap Inc","Communications"],
  ["TTWO","Take-Two Interactive","Communications"],
  ["EA","Electronic Arts","Communications"],
  ["RBLX","Roblox Corp","Communications"],
  ["MTCH","Match Group","Communications"],
  ["BMBL","Bumble Inc","Communications"],
  ["CHTR","Charter Communications","Communications"],
  ["DV","DoubleVerify Holdings","Communications"],
  ["PUBM","PubMatic Inc","Communications"],
  ["AMC","AMC Entertainment Holdings","Communications"],
  ["GME","GameStop Corp","Communications"],
  ["WBD","Warner Bros Discovery","Communications"],
  ["PARA","Paramount Global","Communications"],
  ["FOX","Fox Corp","Communications"],
  ["NYT","New York Times Co","Communications"],
  ["SIRI","Sirius XM Holdings","Communications"],
  ["LBRDA","Liberty Broadband","Communications"],
  ["BILI","Bilibili Inc","Communications"],
  ["IQ","iQIYI Inc","Communications"],
  ["HUYA","HUYA Inc","Communications"],
  ["MOMO","Hello Group","Communications"],
  ["OMC","Omnicom Group","Communications"],
  ["IPG","Interpublic Group","Communications"],
  ["MSGS","Madison Square Garden Sports","Communications"],
  ["FUBO","fuboTV Inc","Communications"],
  ["LGF","Lions Gate Entertainment","Communications"],
  ["IMAX","IMAX Corp","Communications"],
  ["CNK","Cinemark Holdings","Communications"],
  ["ATVI","Activision Blizzard","Communications"],
  ["ASTS","AST SpaceMobile","Communications"],
  ["GRND","Grindr Inc","Communications"],
  ["IAS","Integral Ad Science","Communications"],
  ["SCOR","comScore Inc","Communications"],
  ["CARG","CarGurus Inc","Communications"],
  ["CARS","Cars.com Inc","Communications"],
  ["AMT","American Tower Corp","Real Estate"],
  ["PLD","Prologis Inc","Real Estate"],
  ["EQIX","Equinix Inc","Real Estate"],
  ["CCI","Crown Castle Inc","Real Estate"],
  ["DLR","Digital Realty Trust","Real Estate"],
  ["PSA","Public Storage","Real Estate"],
  ["WELL","Welltower Inc","Real Estate"],
  ["SPG","Simon Property Group","Real Estate"],
  ["O","Realty Income Corp","Real Estate"],
  ["VICI","VICI Properties","Real Estate"],
  ["CSGP","CoStar Group","Real Estate"],
  ["COLD","Americold Realty Trust","Real Estate"],
  ["REXR","Rexford Industrial Realty","Real Estate"],
  ["EGP","EastGroup Properties","Real Estate"],
  ["LEN","Lennar Corp","Real Estate"],
  ["DHI","D.R. Horton Inc","Real Estate"],
  ["PHM","PulteGroup Inc","Real Estate"],
  ["TOL","Toll Brothers","Real Estate"],
  ["NVR","NVR Inc","Real Estate"],
  ["TMHC","Taylor Morrison Home","Real Estate"],
  ["MHO","M/I Homes","Real Estate"],
  ["SKY","Skyline Champion Corp","Real Estate"],
  ["CVCO","Cavco Industries","Real Estate"],
  ["GRBK","Green Brick Partners","Real Estate"],
  ["CCS","Century Communities","Real Estate"],
  ["EQR","Equity Residential","Real Estate"],
  ["AVB","AvalonBay Communities","Real Estate"],
  ["ESS","Essex Property Trust","Real Estate"],
  ["MAA","Mid-America Apartment","Real Estate"],
  ["CPT","Camden Property Trust","Real Estate"],
  ["UDR","UDR Inc","Real Estate"],
  ["VTR","Ventas Inc","Real Estate"],
  ["PEAK","Healthpeak Properties","Real Estate"],
  ["HR","Healthcare Realty Trust","Real Estate"],
  ["OHI","Omega Healthcare Investors","Real Estate"],
  ["LTC","LTC Properties","Real Estate"],
  ["NHI","National Health Investors","Real Estate"],
  ["IIPR","Innovative Industrial Properties","Real Estate"],
  ["GLPI","Gaming and Leisure Properties","Real Estate"],
  ["ADC","Agree Realty Corp","Real Estate"],
  ["NNN","National Retail Properties","Real Estate"],
  ["EPRT","Essential Properties Realty","Real Estate"],
  ["SRC","Spirit Realty Capital","Real Estate"],
  ["NTST","Netstreit Corp","Real Estate"],
  ["FCPT","Four Corners Property Trust","Real Estate"],
  ["STAG","STAG Industrial","Real Estate"],
  ["FR","First Industrial Realty","Real Estate"],
  ["BXP","Boston Properties","Real Estate"],
  ["SLG","SL Green Realty","Real Estate"],
  ["VNO","Vornado Realty Trust","Real Estate"],
  ["KIM","Kimco Realty Corp","Real Estate"],
  ["REG","Regency Centers Corp","Real Estate"],
  ["AKR","Acadia Realty Trust","Real Estate"],
  ["WD","Walker Dunlop","Real Estate"],
  ["CBRE","CBRE Group","Real Estate"],
  ["JLL","Jones Lang LaSalle","Real Estate"],
  ["CWK","Cushman Wakefield","Real Estate"],
  ["RWT","Redwood Trust","Real Estate"],
  ["MFA","MFA Financial","Real Estate"],
  ["SACH","Sachem Capital Corp","Real Estate"],
  ["FOR","Forestar Group","Real Estate"],
  ["NMRK","Newmark Group","Real Estate"],
  ["IVT","InvenTrust Properties","Real Estate"],
  ["RIOT","Riot Platforms","Crypto"],
  ["MARA","Marathon Digital Holdings","Crypto"],
  ["CLSK","CleanSpark Inc","Crypto"],
  ["HUT","Hut 8 Mining Corp","Crypto"],
  ["WULF","TeraWulf Inc","Crypto"],
  ["IREN","Iris Energy Ltd","Crypto"],
  ["BITF","Bitfarms Ltd","Crypto"],
  ["CIFR","Cipher Mining","Crypto"],
  ["BTM","Bitcoin Depot Inc","Crypto"],
  ["SDIG","Stronghold Digital Mining","Crypto"],
  ["HIVE","HIVE Blockchain Technologies","Crypto"],
  ["ARBK","Argo Blockchain","Crypto"],
  ["BTCS","BTCS Inc","Crypto"],
  ["CAN","Canaan Inc","Crypto"],
  ["BTBT","Bit Digital Inc","Crypto"],
  ["MIGI","Mawson Infrastructure Group","Crypto"],
  ["GRIID","Griid Infrastructure","Crypto"],
  ["SLXN","Soluna Holdings","Crypto"],
  ["MATH","Metalpha Technology Holding","Crypto"],
  ["DMGI","DMG Blockchain Solutions","Crypto"],
  ["SPY","SPDR S&P 500 ETF","ETF"],
  ["QQQ","Invesco QQQ Trust","ETF"],
  ["IWM","iShares Russell 2000 ETF","ETF"],
  ["SOXX","iShares PHLX Semiconductor","ETF"],
  ["XLK","Technology Select Sector","ETF"],
  ["XLF","Financial Select Sector","ETF"],
  ["XLE","Energy Select Sector","ETF"],
  ["XLV","Health Care Select Sector","ETF"],
  ["ARKK","ARK Innovation ETF","ETF"],
  ["TQQQ","ProShares UltraPro QQQ","ETF"],
  ["SQQQ","ProShares UltraPro Short QQQ","ETF"],
  ["GLD","SPDR Gold Shares","ETF"],
  ["GDX","VanEck Gold Miners ETF","ETF"],
  ["TLT","20+ Year Treasury ETF","ETF"],
  ["SLV","iShares Silver Trust","ETF"],
  ["GDXJ","VanEck Junior Gold Miners","ETF"],
  ["ARKQ","ARK Autonomous Tech ETF","ETF"],
  ["ARKW","ARK Next Gen Internet ETF","ETF"],
  ["ARKG","ARK Genomic Revolution ETF","ETF"],
  ["BOTZ","Global X Robotics AI ETF","ETF"],
].map(([ticker,name,sector])=>({ticker,name,sector}));

// ── Yahoo Finance v8 Chart API fetch ─────────────────────────────────────────
// No crumb needed · No API key · Works from Vercel
async function fetchCandles(ticker) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${ticker}?interval=1d&range=6mo`;
  const res = await fetch(url, {
    headers: {
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
      "Accept": "application/json",
      "Accept-Language": "en-US,en;q=0.9",
      "Origin": "https://finance.yahoo.com",
      "Referer": "https://finance.yahoo.com/",
    },
  });

  if (!res.ok) return null;
  const data = await res.json();
  const result = data?.chart?.result?.[0];
  if (!result) return null;

  const timestamps = result.timestamp || [];
  const quote = result.indicators?.quote?.[0] || {};
  const adjClose = result.indicators?.adjclose?.[0]?.adjclose || [];
  const opens   = quote.open   || [];
  const highs   = quote.high   || [];
  const lows    = quote.low    || [];
  const closes  = quote.close  || [];
  const volumes = quote.volume || [];

  const candles = [];
  for (let i = 0; i < timestamps.length; i++) {
    const o = opens[i], h = highs[i], l = lows[i], c = closes[i];
    if (o == null || h == null || l == null || c == null) continue;
    candles.push({
      date:   new Date(timestamps[i] * 1000).toISOString().slice(0, 10),
      open:   o,
      high:   h,
      low:    l,
      close:  adjClose[i] ?? c,
      volume: volumes[i] || 0,
    });
  }
  return candles.length >= 20 ? candles : null;
}

// ── ICT Engine ────────────────────────────────────────────────────────────────
function calcATR(candles, period = 14) {
  const trs = [];
  for (let i = 1; i < candles.length; i++) {
    trs.push(Math.max(
      candles[i].high - candles[i].low,
      Math.abs(candles[i].high - candles[i-1].close),
      Math.abs(candles[i].low  - candles[i-1].close)
    ));
  }
  const sl = trs.slice(-period);
  return sl.reduce((a,b)=>a+b,0) / sl.length || candles[0].close * 0.015;
}

function calcAvgVol(candles, period = 20) {
  const s = candles.slice(-period);
  return s.reduce((a,c)=>a+c.volume,0) / s.length;
}

function pivotHighs(c, n = 3) {
  const out = [];
  for (let i = n; i < c.length - n; i++) {
    let ok = true;
    for (let j = i-n; j <= i+n; j++) { if (j!==i && c[j].high >= c[i].high) {ok=false;break;} }
    if (ok) out.push(i);
  }
  return out;
}

function pivotLows(c, n = 3) {
  const out = [];
  for (let i = n; i < c.length - n; i++) {
    let ok = true;
    for (let j = i-n; j <= i+n; j++) { if (j!==i && c[j].low <= c[i].low) {ok=false;break;} }
    if (ok) out.push(i);
  }
  return out;
}

function bullOB(c, atr, lb=40, dm=0.8) {
  for (let i=c.length-1; i>=Math.max(1,c.length-lb); i--) {
    if (c[i].close-c[i].open < atr*dm) continue;
    for (let j=i-1; j>=Math.max(0,i-4); j--)
      if (c[j].close < c[j].open) return {high:c[j].high,low:c[j].low};
  }
  return null;
}

function bearOB(c, atr, lb=40, dm=0.8) {
  for (let i=c.length-1; i>=Math.max(1,c.length-lb); i--) {
    if (c[i].open-c[i].close < atr*dm) continue;
    for (let j=i-1; j>=Math.max(0,i-4); j--)
      if (c[j].close > c[j].open) return {high:c[j].high,low:c[j].low};
  }
  return null;
}

function bullFVG(c, atr, lb=40) {
  const e=c.length-1;
  for (let i=e; i>=Math.max(2,e-lb); i--) {
    const bot=c[i-2].high, top=c[i].low;
    if (top<=bot || top-bot<atr*0.1) continue;
    let ok=true;
    for (let k=i+1;k<=e;k++) if(c[k].close<bot){ok=false;break;}
    if (ok) return {top,bot};
  }
  return null;
}

function bearFVG(c, atr, lb=40) {
  const e=c.length-1;
  for (let i=e; i>=Math.max(2,e-lb); i--) {
    const top=c[i-2].low, bot=c[i].high;
    if (bot>=top || top-bot<atr*0.1) continue;
    let ok=true;
    for (let k=i+1;k<=e;k++) if(c[k].close>top){ok=false;break;}
    if (ok) return {top,bot};
  }
  return null;
}

function bullMSB(c, phIdxs, win=20) {
  const e=c.length-1;
  for (const idx of [...phIdxs].reverse()) {
    const lv=c[idx].high;
    for (let i=idx+1;i<=e;i++) if(c[i].close>lv){if(i>=e-win)return lv;break;}
  }
  return null;
}

function bearMSB(c, plIdxs, win=20) {
  const e=c.length-1;
  for (const idx of [...plIdxs].reverse()) {
    const lv=c[idx].low;
    for (let i=idx+1;i<=e;i++) if(c[i].close<lv){if(i>=e-win)return lv;break;}
  }
  return null;
}

function bullLS(c, plIdxs, win=20) {
  const e=c.length-1;
  for (const idx of plIdxs) {
    if (idx>e-win) continue;
    const lv=c[idx].low;
    for (let i=idx+1;i<=e;i++)
      if(c[i].low<lv && c[i].close>lv && i>=e-win) return true;
  }
  return false;
}

function bearLS(c, phIdxs, win=20) {
  const e=c.length-1;
  for (const idx of phIdxs) {
    if (idx>e-win) continue;
    const lv=c[idx].high;
    for (let i=idx+1;i<=e;i++)
      if(c[i].high>lv && c[i].close<lv && i>=e-win) return true;
  }
  return false;
}

function bullOTE(c, plIdxs, phIdxs) {
  if (!plIdxs.length||!phIdxs.length) return false;
  const pL=plIdxs[plIdxs.length-1], pH=phIdxs[phIdxs.length-1];
  if (pL>=pH) return false;
  const rng=c[pH].high-c[pL].low; if(rng<=0) return false;
  const p=c[c.length-1].close;
  return p>=(c[pH].high-rng*0.786)*0.998 && p<=(c[pH].high-rng*0.618)*1.002;
}

function bearOTE(c, plIdxs, phIdxs) {
  if (!plIdxs.length||!phIdxs.length) return false;
  const pL=plIdxs[plIdxs.length-1], pH=phIdxs[phIdxs.length-1];
  if (pH>=pL) return false;
  const rng=c[pH].high-c[pL].low; if(rng<=0) return false;
  const p=c[c.length-1].close;
  return p>=(c[pL].low+rng*0.618)*0.998 && p<=(c[pL].low+rng*0.786)*1.002;
}

function analyzeICT(ticker, name, sector, candles) {
  if (candles.length < 20) return null;
  const last=candles[candles.length-1], prev=candles[candles.length-2];
  const price=last.close, atr=calcATR(candles);
  const avgVol=calcAvgVol(candles);
  const volRatio=avgVol>0?last.volume/avgVol:1;
  const changePct=prev.close>0?((price-prev.close)/prev.close)*100:0;
  const phIdxs=pivotHighs(candles,3), plIdxs=pivotLows(candles,3);

  const bOB=bullOB(candles,atr), bFVG=bullFVG(candles,atr);
  const bMSB=bullMSB(candles,phIdxs), bLS=bullLS(candles,plIdxs);
  const bOTE=bullOTE(candles,plIdxs,phIdxs);
  const rOB=bearOB(candles,atr), rFVG=bearFVG(candles,atr);
  const rMSB=bearMSB(candles,plIdxs), rLS=bearLS(candles,phIdxs);
  const rOTE=bearOTE(candles,plIdxs,phIdxs);

  const bullScore=(bOB?2:0)+(bFVG?2:0)+(bMSB?2:0)+(bLS?1.5:0)+(bOTE?1:0);
  const bearScore=(rOB?2:0)+(rFVG?2:0)+(rMSB?2:0)+(rLS?1.5:0)+(rOTE?1:0);
  const MIN=1.5;
  if (bullScore<MIN&&bearScore<MIN) return null;

  let bias, sigs=[], score;
  if (bullScore>=bearScore&&bullScore>=MIN) {
    bias='bullish'; score=bullScore;
    if(bOB)sigs.push("OB"); if(bFVG)sigs.push("FVG"); if(bMSB)sigs.push("MSB");
    if(bLS)sigs.push("LS"); if(bOTE)sigs.push("OTE");
  } else {
    bias='bearish'; score=bearScore;
    if(rOB)sigs.push("OB"); if(rFVG)sigs.push("FVG"); if(rMSB)sigs.push("MSB");
    if(rLS)sigs.push("LS"); if(rOTE)sigs.push("OTE");
  }
  if (volRatio>=1.5) score=Math.min(8.5,score+0.5);
  const strength=Math.max(1,Math.min(10,Math.round((score/8.5)*10)));

  const obZ=bias==='bullish'?bOB:rOB;
  const fvZ=bias==='bullish'?bFVG:rFVG;
  const msL=bias==='bullish'?bMSB:rMSB;

  let entry=price,stop,target;
  if (bias==='bullish') {
    stop=obZ?obZ.low-atr*0.5:plIdxs.length?candles[plIdxs[plIdxs.length-1]].low-atr*0.3:price-atr*2;
    target=entry+(entry-stop)*2.5;
  } else {
    stop=obZ?obZ.high+atr*0.5:phIdxs.length?candles[phIdxs[phIdxs.length-1]].high+atr*0.3:price+atr*2;
    target=entry-(stop-entry)*2.5;
  }
  const rr=Math.abs(entry-stop)>0?Math.abs(target-entry)/Math.abs(entry-stop):0;
  const parts=[];
  if(sigs.includes("OB"))parts.push("Order Block");
  if(sigs.includes("FVG"))parts.push("open FVG");
  if(sigs.includes("MSB"))parts.push("structure break");
  if(sigs.includes("LS"))parts.push("liquidity sweep");
  if(sigs.includes("OTE"))parts.push("OTE zone");

  return {
    ticker,name,sector,
    price:+price.toFixed(2),changePct:+changePct.toFixed(2),
    volume:last.volume,avgVolume:Math.round(avgVol),volRatio:+volRatio.toFixed(2),
    signals:sigs,strength,bias,
    description:`${bias==='bullish'?'Bullish':'Bearish'}: ${parts.join(', ')}.`,
    obHigh:obZ?.high??null,obLow:obZ?.low??null,
    fvgTop:fvZ?.top??null,fvgBot:fvZ?.bot??null,msbLevel:msL??null,
    entry:+entry.toFixed(2),stop:+stop.toFixed(2),target:+target.toFixed(2),
    rr:+rr.toFixed(2),atr:+atr.toFixed(2),
  };
}

// ── Handler ───────────────────────────────────────────────────────────────────
module.exports = async (req, res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Cache-Control", "no-store");

  const batchSize = 12; // 12 parallel Yahoo Chart requests — well within limits

  if (req.query.meta !== undefined) {
    return res.json({ total: STOCKS.length, batchSize });
  }

  const batch = parseInt(req.query.batch ?? "0", 10);
  const slice = STOCKS.slice(batch * batchSize, (batch + 1) * batchSize);
  if (!slice.length) return res.json({ results: [], done: true });

  const settled = await Promise.allSettled(
    slice.map(async ({ ticker, name, sector }) => {
      try {
        const candles = await fetchCandles(ticker);
        if (!candles) return null;
        return analyzeICT(ticker, name, sector, candles);
      } catch { return null; }
    })
  );

  const results = settled
    .filter(r => r.status === 'fulfilled' && r.value !== null)
    .map(r => r.value);

  return res.json({
    results,
    done: (batch + 1) * batchSize >= STOCKS.length,
    _debug: {
      batch,
      fetched: slice.length,
      signals: results.length,
      nulls: settled.filter(r=>r.status==='fulfilled'&&r.value===null).length,
      errors: settled.filter(r=>r.status==='rejected').length,
    },
  });
};
